version: "3"
services:
   node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
   volumes:
    - ./src:/bostaApi/src:ro
   environment:
    - NODE_ENV=development
   command: npm start-dev
