version: '3'
services:
  node-app:
    container_name: bosta-node-api-container
    ports:
      - '3000:4000'
    env_file:
      - ./.env
      

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-db: 